import './stencil.core';
/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import './stencil.core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {
  interface HTMLBmCheckboxElement extends HTMLStencilElement {
    'checkboxid': string;
    'initialchecked': boolean;
    'initialvalue': string;
    'labeltext': string;
  }
  var HTMLBmCheckboxElement: {
    prototype: HTMLBmCheckboxElement;
    new (): HTMLBmCheckboxElement;
  };
  interface HTMLElementTagNameMap {
    'bm-checkbox': HTMLBmCheckboxElement;
  }
  interface ElementTagNameMap {
    'bm-checkbox': HTMLBmCheckboxElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'bm-checkbox': JSXElements.BmCheckboxAttributes;
    }
  }
  namespace JSXElements {
    export interface BmCheckboxAttributes extends HTMLAttributes {
      'checkboxid'?: string;
      'initialchecked'?: boolean;
      'initialvalue'?: string;
      'labeltext'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
